services:
  api:
    build: .
    stdin_open: true
    ports:
      - '5000:3000'
    depends_on:
      - mysql8
    environment:
      TZ: UTC
      MYSQL_HOST: mysql8
      BUNDLE_PATH: /usr/local/bundle
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/unicorn.pid && bin/rails s -b 0.0.0.0"
  mysql8:
    platform: linux/x86_64
    image: container-registry.oracle.com/mysql/community-server:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    expose:
      - 13307
    ports:
      - '13307:3306'
    volumes:
      - mysql8-store:/var/lib/mysql
volumes:
  bundle:
  mysql8-store:
